### ISSUE TITLE
WTF?? this isn't oop.

### ISSUE THREAD

**Issue by liammuir** [liammuir/Weather_App#13]
There are three weather components with the same code in a recent unreleased commit. WHYYYYY. THis isn't OOP this is some C crap. Get rid of the seperate components immidiatly!!!!!!

**Comment by liammuir** [comment]
is this how one requests a change?

**Comment by liammuir** [comment]
Someone else: No, we need different data parsing you buffoon. i thought i banned u from this repo

**Comment by davidtollefson** [comment]
Well, I'm not sure what to do with this one. Is the question, "is this how one requests a change?" ?

If so, yes, this is how one goes about saying hey we need to address a particular issue. Maybe even assign it to somebody, and get on with it.

I have created issues on other people's repos which they have then created PRs for and resolved.

**Comment by liammuir** [comment]
cool
